#!/usr/bin/env bash
# build.sh — сборка фронтенда и бэкенда под конкретное окружение.
#
# Использование:
#   ./build.sh local          # localhost + SQLite, devnet
#   ./build.sh dev            # dev-сервер + SQLite, devnet
#   ./build.sh prod           # prod-сервер + PostgreSQL, mainnet
#   ./build.sh dev --env-file build/env/dev.myserver   # свой файл значений
#
# Значения берутся из build/env/<variant> (переопределяется --env-file).
# Отредактируйте файлы в build/env/ под свои серверы.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

VARIANT=""
ENV_FILE=""
SKIP_FRONTEND=0
SKIP_BACKEND=0

usage() {
  sed -n '2,12p' "$0"
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    local|dev|prod)
      [[ -z "$VARIANT" ]] || { echo "only one variant allowed"; usage 1; }
      VARIANT="$1" ;;
    --env-file)   ENV_FILE="$2"; shift ;;
    --skip-frontend) SKIP_FRONTEND=1 ;;
    --skip-backend)  SKIP_BACKEND=1 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown argument: $1"; usage 1 ;;
  esac
  shift
done

[[ -n "$VARIANT" ]] || usage 1
[[ -n "$ENV_FILE" ]] || ENV_FILE="build/env/$VARIANT"
[[ -f "$ENV_FILE" ]] || { echo "env file not found: $ENV_FILE"; exit 1; }

# ---- load values ---------------------------------------------------------
# shellcheck disable=SC1090
source "$ENV_FILE"

# VITE_API_URL может быть пустой (same-origin /api) — проверяем, что задана
[[ "${VITE_API_URL+x}" == "x" ]] || { echo "VITE_API_URL is required in $ENV_FILE"; exit 1; }
[[ "${VITE_SOLANA_CLUSTER+x}" == "x" ]] || { echo "VITE_SOLANA_CLUSTER is required in $ENV_FILE"; exit 1; }
: "${APP_NAME:=$VARIANT}"
: "${GOOS:=linux}"
: "${GOARCH:=amd64}"
: "${CGO_ENABLED:=1}"

DIST_DIR="build/dist/$VARIANT"
echo "=== build: $VARIANT ($ENV_FILE) ==="
echo "    api:  $VITE_API_URL"
echo "    sol:  $VITE_SOLANA_CLUSTER"

# ---- frontend ------------------------------------------------------------
if [[ "$SKIP_FRONTEND" -eq 0 ]]; then
  command -v npm >/dev/null || { echo "npm not found"; exit 1; }
  echo "--- frontend: npm ci && vite build"
  (cd frontend && npm ci --no-audit --no-fund)
  # VITE_* values are inlined into the bundle at build time
  (cd frontend && \
    VITE_API_URL="$VITE_API_URL" \
    VITE_SOLANA_CLUSTER="$VITE_SOLANA_CLUSTER" \
    VITE_SOLANA_RPC="${VITE_SOLANA_RPC:-}" \
    npm run build -- --outDir "../$DIST_DIR/frontend" --emptyOutDir)
  echo "    -> $DIST_DIR/frontend"
fi

# ---- backend -------------------------------------------------------------
if [[ "$SKIP_BACKEND" -eq 0 ]]; then
  command -v go >/dev/null || { echo "go toolchain not found"; exit 1; }
  echo "--- backend: go build ($GOOS/$GOARCH)"
  GOOS="$GOOS" GOARCH="$GOARCH" CGO_ENABLED="$CGO_ENABLED" \
    go build -trimpath -o "$DIST_DIR/server" ./cmd/server
  echo "    -> $DIST_DIR/server"
fi

# ---- runtime config (.env) + deploy assets --------------------------------
ENV_OUT="$DIST_DIR/.env"
cat > "$ENV_OUT" <<EOF
# Generated by build.sh ($VARIANT) — do not commit
APP_NAME=$APP_NAME
DB_TYPE=$DB_TYPE
DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-}
DB_USER=${DB_USER:-}
DB_PASSWORD=${DB_PASSWORD:-}
DB_NAME=${DB_NAME:-}
DB_SSLMODE=${DB_SSLMODE:-disable}
SQLITE_PATH=${SQLITE_PATH:-}
SERVER_PORT=$SERVER_PORT
FREE_CHECK_LIMIT=${FREE_CHECK_LIMIT:-3}
SOLANA_USE_DEVNET=$SOLANA_USE_DEVNET
SOLANA_PAYMENT_ADDR=${SOLANA_PAYMENT_ADDR:-}
SOLANA_RPC_URL=${SOLANA_RPC_URL:-}
ADMIN_API_KEY=${ADMIN_API_KEY:-}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
JWT_SECRET=${JWT_SECRET:-}
EOF

# scanner + whitelist travel with the build (live monitor data source)
cp solana_scan.py solana_programs.json "$DIST_DIR/"
[[ -d migrations ]] && cp -r migrations "$DIST_DIR/"

echo "--- config -> $ENV_OUT"
echo "=== done: $DIST_DIR (frontend/ server .env solana_scan.py migrations/)"
echo "Run:  cd $DIST_DIR && ./server"
